### ISSUE TITLE
Icon SpritRadar

### ISSUE THREAD

**Issue by samhae** [fravaccaro/harbour-themepack-numix-circle#4]
Would be nice :)

Maybe testdrive could be a matching icon.

**Comment by fravaccaro** [comment]
Released in 0.4.2 :)

**Comment by samhae** [comment]
Didn't work :p

Thank you for your great work!

**Comment by fravaccaro** [comment]
Does it show?

Thanks :)

**Comment by samhae** [comment]
Nope, still the original image.

**Comment by samhae** [comment]
SpritRadar not spiritradar 😁

**Comment by fravaccaro** [comment]
oooops...fixed :)
